### ISSUE TITLE
rectify.cpp文件中为什么对图像做缩放？

### ISSUE THREAD

**Issue by yanglittleSheep** [WisdomF0/long-short_focal_calibration#3]
博主，您好，请问在立体校正 文件中为什么把图片缩放到（2560，1440）这个尺寸，这是个经验值吗？我也注意到了长短焦的相机的图像分辨率是不同的。缩放操作是不是会改变对应的内参矩阵？

**Comment by WisdomF0** [comment]
你好，长焦相机的分辨率是3840x2160的，短焦相机分辨率是1920x1080的，不统一分辨率理论上是可以标定外参的，但是可能是我使用C++和OpenCV代码的能力有限，我标出来效果不太好。Matlab里有一个立体标定工具箱，但是需要统一双目的分辨率，因为两个分辨率差太多所以我就选择了中间的2k分辨率（2560，1440）统一成一样的尺寸，所以在rectify中使用外参之前要改变一下图片的分辨率。而且图片缩放是会对内参有影响的，不过大概只是一个缩放倍率的关系，比如长焦的缩放后内参的第一行要乘 2560 / 3840，第二行要乘 1440 / 2160，这个关系有点误差，可能还有个常数项的关系。
我只是个本科生，这个项目是我做本科毕设的一部分，如果你有更好的解决和改进的方法，也希望可以联系一下我。

**Comment by yanglittleSheep** [comment]
明白了，后续有新方案可多多交流！
